version: '3.4'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    # This is the one that makes the magic
    volumes:
    - "./:/app"
    ports:
      - '8000:3000'
    networks:
      - geos-network
    env_file: .env
#    environment:
#      - REDIS_URL=redis://redis:6379
#    links:
#      - redis
#  redis:
#    image: redis:latest
#    ports:
#      - '6379:6379'
networks:
  geos-network: