require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SurveysController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # Survey. As you add validations to Survey, be sure to
  # adjust the attributes here as well.
  let(:state) { create :state }
  let(:valid_attributes) { attributes_for(:survey).merge(state_id: state.to_param) }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurveysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # stubbing slow external call
  before { allow_any_instance_of(Survey).to receive(:validate_url_with_surveygizimo).and_return(true) }

  describe 'GET #index' do
    it 'assigns all surveys as @surveys' do
      survey = Survey.create! valid_attributes
      get :index, session: valid_session
      expect(assigns(:surveys)).to eq([survey])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested survey as @survey' do
      survey = Survey.create! valid_attributes
      get :show, id: survey.to_param, session: valid_session
      expect(assigns(:survey)).to eq(survey)
    end
  end

  describe 'GET #new' do
    it 'assigns a new survey as @survey' do
      get :new, session: valid_session
      expect(assigns(:survey)).to be_a_new(Survey)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested survey as @survey' do
      survey = Survey.create! valid_attributes
      get :edit, id: survey.to_param, session: valid_session
      expect(assigns(:survey)).to eq(survey)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Survey' do
        expect do
          post :create, survey: valid_attributes, session: valid_session
        end.to change(Survey, :count).by(1)
      end

      it 'assigns a newly created survey as @survey' do
        post :create, survey: valid_attributes, session: valid_session
        expect(assigns(:survey)).to be_a(Survey)
        expect(assigns(:survey)).to be_persisted
      end

      it 'redirects to the created survey' do
        post :create, survey: valid_attributes, session: valid_session
        expect(response).to redirect_to(Survey.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved survey as @survey' do
        post :create, survey: invalid_attributes, session: valid_session
        expect(assigns(:survey)).to be_a_new(Survey)
      end

      it "re-renders the 'new' template" do
        post :create, survey: invalid_attributes, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) { { name: 'New Name' } }

      it 'updates the requested survey' do
        survey = Survey.create! valid_attributes
        put :update, id: survey.to_param, survey: new_attributes, session: valid_session
        survey.reload
        expect(survey.name).to eq 'New Name'
      end

      it 'assigns the requested survey as @survey' do
        survey = Survey.create! valid_attributes
        put :update, id: survey.to_param, survey: valid_attributes, session: valid_session
        expect(assigns(:survey)).to eq(survey)
      end

      it 'redirects to the survey' do
        survey = Survey.create! valid_attributes
        put :update, id: survey.to_param, survey: valid_attributes, session: valid_session
        expect(response).to redirect_to(survey)
      end
    end

    context 'with invalid params' do
      it 'assigns the survey as @survey' do
        survey = Survey.create! valid_attributes
        put :update, id: survey.to_param, survey: invalid_attributes, session: valid_session
        expect(assigns(:survey)).to eq(survey)
      end

      it "re-renders the 'edit' template" do
        survey = Survey.create! valid_attributes
        put :update, id: survey.to_param, survey: invalid_attributes, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested survey' do
      survey = Survey.create! valid_attributes
      expect do
        delete :destroy, id: survey.to_param, session: valid_session
      end.to change(Survey, :count).by(-1)
    end

    it 'redirects to the surveys list' do
      survey = Survey.create! valid_attributes
      delete :destroy, id: survey.to_param, session: valid_session
      expect(response).to redirect_to(surveys_url)
    end
  end
end
