require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SurveyAnswersController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # SurveyAnswer. As you add validations to SurveyAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { attributes_for :survey_answer }

  let(:invalid_attributes) { { value: '' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurveyAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all survey_answers as @survey_answers' do
      survey_answer = SurveyAnswer.create! valid_attributes
      get :index, session: valid_session
      expect(assigns(:survey_answers)).to eq([survey_answer])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested survey_answer as @survey_answer' do
      survey_answer = SurveyAnswer.create! valid_attributes
      get :show, id: survey_answer.to_param, session: valid_session
      expect(assigns(:survey_answer)).to eq(survey_answer)
    end
  end

  describe 'GET #new' do
    it 'assigns a new survey_answer as @survey_answer' do
      get :new, session: valid_session
      expect(assigns(:survey_answer)).to be_a_new(SurveyAnswer)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested survey_answer as @survey_answer' do
      survey_answer = SurveyAnswer.create! valid_attributes
      get :edit, id: survey_answer.to_param, session: valid_session
      expect(assigns(:survey_answer)).to eq(survey_answer)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new SurveyAnswer' do
        expect do
          post :create, survey_answer: valid_attributes, session: valid_session
        end.to change(SurveyAnswer, :count).by(1)
      end

      it 'assigns a newly created survey_answer as @survey_answer' do
        post :create, survey_answer: valid_attributes, session: valid_session
        expect(assigns(:survey_answer)).to be_a(SurveyAnswer)
        expect(assigns(:survey_answer)).to be_persisted
      end

      it 'redirects to the created survey_answer' do
        post :create, survey_answer: valid_attributes, session: valid_session
        expect(response).to redirect_to(SurveyAnswer.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved survey_answer as @survey_answer' do
        post :create, survey_answer: invalid_attributes, session: valid_session
        expect(assigns(:survey_answer)).to be_a_new(SurveyAnswer)
      end

      it "re-renders the 'new' template" do
        post :create, survey_answer: invalid_attributes, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) { { value: 'New Value' } }

      it 'updates the requested survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        put :update, id: survey_answer.to_param, survey_answer: new_attributes, session: valid_session
        survey_answer.reload
        expect(survey_answer.value).to eq 'New Value'
      end

      it 'assigns the requested survey_answer as @survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        put :update, id: survey_answer.to_param, survey_answer: valid_attributes, session: valid_session
        expect(assigns(:survey_answer)).to eq(survey_answer)
      end

      it 'redirects to the survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        put :update, id: survey_answer.to_param, survey_answer: valid_attributes, session: valid_session
        expect(response).to redirect_to(survey_answer)
      end
    end

    context 'with invalid params' do
      it 'assigns the survey_answer as @survey_answer' do
        survey_answer = SurveyAnswer.create! valid_attributes
        put :update, id: survey_answer.to_param, survey_answer: invalid_attributes, session: valid_session
        expect(assigns(:survey_answer)).to eq(survey_answer)
      end

      it "re-renders the 'edit' template" do
        survey_answer = SurveyAnswer.create! valid_attributes
        put :update, id: survey_answer.to_param, survey_answer: invalid_attributes, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested survey_answer' do
      survey_answer = SurveyAnswer.create! valid_attributes
      expect do
        delete :destroy, id: survey_answer.to_param, session: valid_session
      end.to change(SurveyAnswer, :count).by(-1)
    end

    it 'redirects to the survey_answers list' do
      survey_answer = SurveyAnswer.create! valid_attributes
      delete :destroy, id: survey_answer.to_param, session: valid_session
      expect(response).to redirect_to(survey_answers_url)
    end
  end
end
