require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe SurveySectionsController, type: :controller do
  login_admin

  # This should return the minimal set of attributes required to create a valid
  # SurveySection. As you add validations to SurveySection, be sure to
  # adjust the attributes here as well.
  let(:survey_id) { create(:survey).to_param }
  let(:valid_attributes) { attributes_for :survey_section, survey_id: survey_id }

  let(:invalid_attributes) { { name: '' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SurveySectionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'assigns all survey_sections as @survey_sections' do
      survey_section = SurveySection.create! valid_attributes
      get :index, session: valid_session
      expect(assigns(:survey_sections)).to eq([survey_section])
    end
  end

  describe 'GET #show' do
    it 'assigns the requested survey_section as @survey_section' do
      survey_section = SurveySection.create! valid_attributes
      get :show, id: survey_section.to_param, session: valid_session
      expect(assigns(:survey_section)).to eq(survey_section)
    end
  end

  describe 'GET #new' do
    it 'assigns a new survey_section as @survey_section' do
      get :new, session: valid_session
      expect(assigns(:survey_section)).to be_a_new(SurveySection)
    end
  end

  describe 'GET #edit' do
    it 'assigns the requested survey_section as @survey_section' do
      survey_section = SurveySection.create! valid_attributes
      get :edit, id: survey_section.to_param, session: valid_session
      expect(assigns(:survey_section)).to eq(survey_section)
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new SurveySection' do
        expect do
          post :create, survey_section: valid_attributes, session: valid_session
        end.to change(SurveySection, :count).by(1)
      end

      it 'assigns a newly created survey_section as @survey_section' do
        post :create, survey_section: valid_attributes, session: valid_session
        expect(assigns(:survey_section)).to be_a(SurveySection)
        expect(assigns(:survey_section)).to be_persisted
      end

      it 'redirects to the created survey_section' do
        post :create, survey_section: valid_attributes, session: valid_session
        expect(response).to redirect_to(SurveySection.last)
      end
    end

    context 'with invalid params' do
      it 'assigns a newly created but unsaved survey_section as @survey_section' do
        post :create, survey_section: invalid_attributes, session: valid_session
        expect(assigns(:survey_section)).to be_a_new(SurveySection)
      end

      it "re-renders the 'new' template" do
        post :create, survey_section: invalid_attributes, session: valid_session
        expect(response).to render_template('new')
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) { { name: 'New Name' } }

      it 'updates the requested survey_section' do
        survey_section = SurveySection.create! valid_attributes
        put :update, id: survey_section.to_param, survey_section: new_attributes, session: valid_session
        survey_section.reload
        expect(survey_section.name).to eq 'New Name'
      end

      it 'assigns the requested survey_section as @survey_section' do
        survey_section = SurveySection.create! valid_attributes
        put :update, id: survey_section.to_param, survey_section: valid_attributes, session: valid_session
        expect(assigns(:survey_section)).to eq(survey_section)
      end

      it 'redirects to the survey_section' do
        survey_section = SurveySection.create! valid_attributes
        put :update, id: survey_section.to_param, survey_section: valid_attributes, session: valid_session
        expect(response).to redirect_to(survey_section)
      end
    end

    context 'with invalid params' do
      it 'assigns the survey_section as @survey_section' do
        survey_section = SurveySection.create! valid_attributes
        put :update, id: survey_section.to_param, survey_section: invalid_attributes, session: valid_session
        expect(assigns(:survey_section)).to eq(survey_section)
      end

      it "re-renders the 'edit' template" do
        survey_section = SurveySection.create! valid_attributes
        put :update, id: survey_section.to_param, survey_section: invalid_attributes, session: valid_session
        expect(response).to render_template('edit')
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested survey_section' do
      survey_section = SurveySection.create! valid_attributes
      expect do
        delete :destroy, id: survey_section.to_param, session: valid_session
      end.to change(SurveySection, :count).by(-1)
    end

    it 'redirects to the survey_sections list' do
      survey_section = SurveySection.create! valid_attributes
      delete :destroy, id: survey_section.to_param, session: valid_session
      expect(response).to redirect_to(survey_sections_url)
    end
  end
end
